env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
#   # quotes:
#   #   - error
#   #   - single
#   # semi:
#     # - error
#     # - always
